---
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-paginate
exclude:
- "/vendor/"
title: 진혀크의 코딩잼
subtitle: Joyful Programmer JH!
email: faill456@naver.com
name: Jinhyuk Choi
description: 'Enjoy and be the Best'
baseurl: ''
url: https://jinhyukoo.github.io
plugins_dir:
- jekyll-sitemap
cover: "/assets/header_image.jpg"
logo: "/assets/logo.jpg"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
highlightjs_theme: monokai-sublime
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archive
  comments: true
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
disqus_shortname: jinhyukoo
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
social:
- name: GitHub
  icon: github
  username: jinhyukoo
  url: https://github.com/jinhyukoo
  desc: Fork me on GitHub
  share: false
protocols:
  fb_image: "/assets/logo.jpg"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: "/assets/logo.jpg"
  os_repo: https://github.com/bencentra/centrarium.com
  os_rcs_type: git
  os_src: git@github.com:bencentra/centrarium.com.git
